# Generated by Django 5.1.7 on 2025-03-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_student_signup_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['username'], 'verbose_name': 'Login', 'verbose_name_plural': 'Logins'},
        ),
        migrations.CreateModel(
            name='teacher_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.login')),
            ],
        ),
    ]
