# Generated by Django 5.1.7 on 2025-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_alter_login_options_teacher_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_signup',
            name='department',
            field=models.CharField(choices=[('social', 'Social'), ('biology', 'Biology'), ('maths', 'Maths')], max_length=100),
        ),
    ]
