# Generated by Django 5.1.7 on 2025-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_rename_student_signup_studentsignup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='teachersignup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
