# Generated by Django 5.1.7 on 2025-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_studentsignup_image_teachersignup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
