# Generated by Django 5.1.7 on 2025-03-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_alter_studentsignup_image_alter_teachersignup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
