# Generated by Django 5.1.7 on 2025-03-17 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
