# Generated by Django 5.1.7 on 2025-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_exammodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammodel',
            old_name='duration',
            new_name='duration1',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='duration2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
