# Generated by Django 5.1.7 on 2025-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0016_alter_exammodel_duration1_alter_exammodel_duration2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='total_mark',
            field=models.IntegerField(null=True),
        ),
    ]
