# Generated by Django 5.1.7 on 2025-03-17 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0017_alter_exammodel_total_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='duration1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='duration2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='total_mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
