# Generated by Django 5.1.7 on 2025-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0019_alter_exammodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
