# Generated by Django 5.1.7 on 2025-03-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0022_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
